<#
.SYNOPSIS
  Deploy .kiro-template -> per-repo .kiro/

.DESCRIPTION
  Sync shared + appropriate overlay từ .kiro-template vào từng repo's .kiro/ folder.
  Tương tự sync.ps1 cho Windsurf nhưng target .kiro/ structure.

.PARAMETER Repo
  Tên repo cần sync. Default: all repos.

.PARAMETER Mirror
  Nếu set, xóa file trong dest không có ở source.

.PARAMETER DryRun
  Chỉ show preview, không thực sự copy.

.EXAMPLE
  .\sync-kiro.ps1
  .\sync-kiro.ps1 -Repo health_system
  .\sync-kiro.ps1 -Mirror -DryRun
#>

param(
    [ValidateSet('HealthGuard','health_system','Iot_Simulator_clean','healthguard-model-api','PM_REVIEW','all')]
    [string]$Repo = 'all',

    [switch]$Mirror,

    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

# === Config ===
$TEMPLATE = $PSScriptRoot
$ROOT = Split-Path (Split-Path (Split-Path $TEMPLATE -Parent) -Parent) -Parent

$RepoConfig = @{
    'HealthGuard' = @{
        Path = Join-Path $ROOT 'HealthGuard'
        Overlays = @('express-prisma', 'react-vite')
        Stack = 'Express+Prisma (BE), Vite+React (FE)'
        Trunk = 'develop'
    }
    'health_system' = @{
        Path = Join-Path $ROOT 'health_system'
        Overlays = @('flutter', 'fastapi')
        Stack = 'Flutter (mobile), FastAPI (BE)'
        Trunk = 'develop'
    }
    'Iot_Simulator_clean' = @{
        Path = Join-Path $ROOT 'Iot_Simulator_clean'
        Overlays = @('fastapi')
        Stack = 'Python FastAPI (api_server + simulator-web)'
        Trunk = 'develop'
    }
    'healthguard-model-api' = @{
        Path = Join-Path $ROOT 'healthguard-model-api'
        Overlays = @('fastapi')
        Stack = 'Python FastAPI (ML model serving)'
        Trunk = 'master'
    }
    'PM_REVIEW' = @{
        Path = Join-Path $ROOT 'PM_REVIEW'
        Overlays = @('docs-sql')
        Stack = 'Docs + SQL canonical schema'
        Trunk = 'main'
    }
}

# === Helpers ===

function Write-Step($Message) {
    Write-Host ">> $Message" -ForegroundColor Cyan
}

function Write-Action($Verb, $Path) {
    $color = switch ($Verb) {
        'COPY'   { 'Green' }
        'SKIP'   { 'DarkGray' }
        'DELETE' { 'Yellow' }
        default  { 'White' }
    }
    Write-Host ("  [{0,-6}] {1}" -f $Verb, $Path) -ForegroundColor $color
}

function Sync-Directory {
    param(
        [string]$Source,
        [string]$Dest,
        [switch]$Mirror,
        [switch]$DryRun
    )
    if (-not (Test-Path $Source)) {
        Write-Action 'SKIP' "Source missing: $Source"
        return
    }

    if (-not (Test-Path $Dest)) {
        if ($DryRun) {
            Write-Action 'COPY' "Create dir: $Dest"
        } else {
            New-Item -Path $Dest -ItemType Directory -Force | Out-Null
        }
    }

    if ($Mirror -and (Test-Path $Dest)) {
        Get-ChildItem -Path $Dest -Recurse -File | ForEach-Object {
            $relativePath = $_.FullName.Substring($Dest.Length).TrimStart('\','/')
            $sourcePath = Join-Path $Source $relativePath
            if (-not (Test-Path $sourcePath)) {
                if ($DryRun) {
                    Write-Action 'DELETE' $_.FullName
                } else {
                    Remove-Item $_.FullName -Force
                    Write-Action 'DELETE' $_.FullName
                }
            }
        }
    }

    Get-ChildItem -Path $Source -Recurse -File | ForEach-Object {
        $relativePath = $_.FullName.Substring($Source.Length).TrimStart('\','/')
        $destPath = Join-Path $Dest $relativePath
        $destDir = Split-Path $destPath -Parent
        if ($DryRun) {
            Write-Action 'COPY' "$relativePath"
        } else {
            if (-not (Test-Path $destDir)) {
                New-Item -Path $destDir -ItemType Directory -Force | Out-Null
            }
            Copy-Item $_.FullName $destPath -Force
        }
    }
}

function Write-RepoContext {
    param(
        [string]$RepoName,
        [hashtable]$Config,
        [string]$KiroDir,
        [switch]$DryRun
    )
    $steeringDir = Join-Path $KiroDir 'steering'
    if (-not (Test-Path $steeringDir) -and -not $DryRun) {
        New-Item -Path $steeringDir -ItemType Directory -Force | Out-Null
    }
    $path = Join-Path $steeringDir 'repo-context.md'
    $overlaysText = if ($Config.Overlays.Count -gt 0) { $Config.Overlays -join ', ' } else { '(none)' }
    $content = @"
---
inclusion: always
---

# Repo Context — $RepoName

**Auto-generated by sync-kiro.ps1.** Edit template để thay đổi.

## This repo

- **Name:** ``$RepoName``
- **Path:** ``$($Config.Path)``
- **Stack:** $($Config.Stack)
- **Overlays applied:** ``$overlaysText``
- **Trunk branch:** ``$($Config.Trunk)``

## Other repos in workspace

| Repo | Path | Stack |
|---|---|---|
| HealthGuard | ``d:\DoAn2\VSmartwatch\HealthGuard`` | Admin web (Express + Prisma + Vite) |
| health_system | ``d:\DoAn2\VSmartwatch\health_system`` | Mobile (Flutter) + BE (FastAPI) |
| Iot_Simulator_clean | ``d:\DoAn2\VSmartwatch\Iot_Simulator_clean`` | IoT sim (Python FastAPI) |
| healthguard-model-api | ``d:\DoAn2\VSmartwatch\healthguard-model-api`` | Model API (FastAPI) |
| PM_REVIEW | ``d:\DoAn2\VSmartwatch\PM_REVIEW`` | Docs + SQL + PM |

## Working rules

- Default: stay within this repo's source code.
- Feature chạm repo khác → flag rõ + đề xuất task plan cross-repo.
- ``PM_REVIEW`` luôn là source of truth cho spec — verify UC trước khi implement.

## Last sync

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')
"@

    if ($DryRun) {
        Write-Action 'COPY' "steering/repo-context.md (auto-generated)"
    } else {
        # UTF-8 no BOM — deterministic encoding to avoid mojibake
        [System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
    }
}

function Sync-Repo {
    param(
        [string]$Name,
        [hashtable]$Config,
        [switch]$Mirror,
        [switch]$DryRun
    )
    Write-Step "Syncing $Name ($($Config.Stack))"

    if (-not (Test-Path $Config.Path)) {
        Write-Host "  [ERROR] Repo path missing: $($Config.Path)" -ForegroundColor Red
        return
    }

    $kiroDir = Join-Path $Config.Path '.kiro'

    # 1. Sync shared steering → .kiro/steering
    Sync-Directory `
        -Source (Join-Path $TEMPLATE 'shared\steering') `
        -Dest (Join-Path $kiroDir 'steering') `
        -Mirror:$Mirror -DryRun:$DryRun

    # 2. Overlay steering → .kiro/steering (additive)
    foreach ($overlay in $Config.Overlays) {
        $overlaySteeringDir = Join-Path $TEMPLATE "overlays\$overlay\steering"
        if (Test-Path $overlaySteeringDir) {
            Sync-Directory `
                -Source $overlaySteeringDir `
                -Dest (Join-Path $kiroDir 'steering') `
                -DryRun:$DryRun
        }
    }

    # 3. Sync shared skills → .kiro/skills
    Sync-Directory `
        -Source (Join-Path $TEMPLATE 'shared\skills') `
        -Dest (Join-Path $kiroDir 'skills') `
        -Mirror:$Mirror -DryRun:$DryRun

    # 4. Sync hooks → .kiro/hooks
    Sync-Directory `
        -Source (Join-Path $TEMPLATE 'shared\hooks') `
        -Dest (Join-Path $kiroDir 'hooks') `
        -Mirror:$Mirror -DryRun:$DryRun

    # 5. Copy topology.md (cross-repo reference)
    $topologySrc = Join-Path (Split-Path $TEMPLATE -Parent) '.windsurf-template\topology.md'
    if (Test-Path $topologySrc) {
        $topologyDest = Join-Path $kiroDir 'topology.md'
        if ($DryRun) {
            Write-Action 'COPY' "topology.md"
        } else {
            Copy-Item $topologySrc $topologyDest -Force
        }
    }

    # 6. Sync settings (MCP config)
    $settingsSrc = Join-Path $TEMPLATE 'shared\settings'
    if (Test-Path $settingsSrc) {
        Sync-Directory `
            -Source $settingsSrc `
            -Dest (Join-Path $kiroDir 'settings') `
            -DryRun:$DryRun
    }

    # 7. Generate repo-context.md
    Write-RepoContext -RepoName $Name -Config $Config -KiroDir $kiroDir -DryRun:$DryRun

    Write-Host "  Done: $Name`n" -ForegroundColor Green
}

# === Main ===

Write-Host ""
Write-Host "VSmartwatch .kiro-template sync" -ForegroundColor Magenta
Write-Host "Template: $TEMPLATE" -ForegroundColor DarkGray
if ($Mirror) { Write-Host "Mode: MIRROR (delete extras)" -ForegroundColor Yellow }
else { Write-Host "Mode: UPDATE (preserve extras)" -ForegroundColor Green }
if ($DryRun) { Write-Host "DryRun: ON" -ForegroundColor Yellow }
Write-Host ""

if (-not (Test-Path $TEMPLATE)) {
    Write-Host "[ERROR] Template missing: $TEMPLATE" -ForegroundColor Red
    exit 1
}

$repos = if ($Repo -eq 'all') { $RepoConfig.Keys } else { @($Repo) }

# Branch guard: warn if any target repo is on a non-chore/non-trunk branch
foreach ($r in $repos) {
    $repoPath = $RepoConfig[$r].Path
    if (Test-Path (Join-Path $repoPath '.git')) {
        $branch = git -C $repoPath branch --show-current 2>$null
        if ($branch -and $branch -notmatch '^(chore/|main$|master$|develop$)') {
            Write-Host "  [WARN] $r is on branch '$branch'. .kiro/ changes should be on chore/* branch." -ForegroundColor Yellow
        }
    }
}

foreach ($r in $repos) {
    Sync-Repo -Name $r -Config $RepoConfig[$r] -Mirror:$Mirror -DryRun:$DryRun
}

Write-Host "Done. Repos synced: $($repos.Count)" -ForegroundColor Magenta
